global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask-apps'
    static_configs:
      - targets:
        - 'ipapi-app:5000'
        - 'jsonip-app:5000'
        labels:
          group: 'flask-applications'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']